### ISSUE TITLE
Instance vars with an array panics the resource

### ISSUE THREAD

**Issue by makohoek** [arbourd/concourse-slack-alert-resource#105]
The current implementation for instanced pipelines is limited to string=string key=values.

However, the documentation state that each value can be an arbitrary json data:
>  instance vars can hold arbitrary YAML/JSON data.

See:  https://concourse-ci.org/instanced-pipelines.html

This includes arrays.

When using an array with this resource, it fails to unmarshall the `$BUILD_PIPELINE_INSTANCE_VARS`:

```
 panic: could not unmarshall $BUILD_PIPELINE_INSTANCE_VARS: {"days":["Monday","Tuesday","Wednesday","Thursday","Friday"],start_time":"08:00 PM","stop_time":"09:00 PM"}

  goroutine 1 [running]:
  github.com/arbourd/concourse-slack-alert-resource/concourse.NewBuildMetadata({0x0?, 0x0?})
  	/go/src/github.com/arbourd/concourse-slack-alert-resource/concourse/build.go:60 +0x874
  main.out(0xc000176000, {0x7ffef20f0dd1, 0xe})
  	/go/src/github.com/arbourd/concourse-slack-alert-resource/out/main.go:140 +0xa8
  main.main()
```

I have noticed that other implementation (such as https://github.com/mockersf/concourse-slack-notifier) do this differently and handle it well.
There is an ongoing PR https://github.com/mockersf/concourse-slack-notifier/pull/86 about this topic.

Since both this project and `mockersf/concourse-slack-notifier` seemed to have lost interest from their maintainers, I have a forked, updated version with instance var support here:

https://github.com/makohoek/concourse-slack-notifier/pull/5

Note that I would prefer to fix `arbourd/concourse-slack-alert-resource` but I have no Go experience at all.

**Comment by arbourd** [comment]
I think #108 is the fix for this, but I'd love you take a look at it or give it a test.

**Comment by arbourd** [comment]
This is merged in and available via the tag `main` @makohoek. Can you give it a test for me?

**Comment by arbourd** [comment]
Live with `v0.17.0`

**Comment by makohoek** [comment]
Hi @arbourd . Thanks a bunch for working on this. I'm sorry I took this much time to answer, I completely missed the notifications.

I can confirm that:
- with: `v0.16.2` I *reproduce* the issue.
- with `v0.17.0` I *cannot reproduce* the issue.

So I confirm it's fixed. Thanks again for maintaining this :+1:
