### ISSUE TITLE
Make this project into a generic notification resource type?

### ISSUE THREAD

**Issue by higuoxing** [arbourd/concourse-slack-alert-resource#129]
Hi,

Recently, my team have to migrate our Concourse notification from Slack to Google Chat. Based on your high quality codes, I can easily implement the notification resource for Google Chat. What do you think of adding an additional backend to `concourse-slack-alert-resource`? I've already implemented a prototype in https://github.com/higuoxing/concourse-google-chat-alert-resource.

It looks like:

![image](https://github.com/arbourd/concourse-slack-alert-resource/assets/21099318/1f5a5009-7bd1-4a84-80b5-3856da082f84)

**Comment by arbourd** [comment]
Not a bad idea, but this project is kinda on life support as I am not using Concourse anymore. I'm not sure we'd wanna add another backend to not support?
