### ISSUE TITLE
Allow the ability to create a minimal slack alert

### ISSUE THREAD

**Issue by theskipster** [arbourd/concourse-slack-alert-resource#32]
When there are a lot of deployments, the channel it is in gets very noisy.  I was wondering if we could add a parameter to allow a minimal alert that might look like this:

<img width="640" alt="screenshot 2018-07-09 16 22 24" src="https://user-images.githubusercontent.com/1102888/42570087-c0da3440-84e0-11e8-9184-faa6be1d150e.png">

The link would be to the corresponding concourse build.

**Comment by arbourd** [comment]
I think there is definitely an argument for a minimal version of the Slack alert, but at this time, I'm not sure how we would draw it out.

Either way, at this time, we wouldn't be able to programatically set a message to something like `service-version deployed` based on the nature of the resource.

If you need something super customizable, I'd check out https://github.com/cloudfoundry-community/slack-notification-resource

**Comment by theskipster** [comment]
Just to add context, this is how I see the message:
`[
	{
		"type": "section",
		"text": {
			"type": "mrkdwn",
			"text": ":concourse_pass: `qcs/prod-feature-flags` version <https://ci.pipeline.k8s.qlikcloud.io/teams/main/pipelines/qcs/jobs/prod-feature-flags/builds/537|#537> deployed successfully."
		}
	}
]`

**Comment by arbourd** [comment]
I think a good option for this might just be the `message` or `message_file` contents with a link to the build.

**Comment by arbourd** [comment]
Closing because I don't think this will ever be done. If someone would like to take it on, we can reopen.
