### ISSUE TITLE
This resource is compatible with mattermost

### ISSUE THREAD

**Issue by EugenMayer** [arbourd/concourse-slack-alert-resource#52]
Just leaving it here for all the people googling for that - this ressource can properly post to a mattermost incoming hook.

**Comment by EugenMayer** [comment]
@arbourd Maybe it would be interesting stating that in your readme?

Since mattermost does supprt slack in common as incoming hook, it is easy to use this resource to have pretty nice mattermost notifications too.

- create a simple mattermost incoming hook
- use this as webhook here in source

Anything else is just like using slack - but i would say it is worth a mention. E.g. cloudfronts slack resource does not work with mattermost in contrary

**Comment by arbourd** [comment]
First I've heard of MatterMost. I don't think we want to support it and if it's the README it becomes a requirement. Technically, this will support anything that implements the Slack API 1-1 😬

**Comment by EugenMayer** [comment]
Well i would say mattermost is the best well known alternative to slack being self hosted and even free of charge / OSS: https://github.com/mattermost/mattermost-server 15k stars with 3k forks is probably significant enough, quite close behind rocket-chat, which is far older and is falling of quiet a bit.

Anyway, it's your choice, i am not a mattermost vendor or need to praise it :) We just are on our path to migrate to it from hipchat datacenter and thus i was dealing with all the integration points. Fair enough if you do not want to opt in for mattermost in any particular way
