### ISSUE TITLE
latest docker image tag is broke

### ISSUE THREAD

**Issue by EugenMayer** [arbourd/concourse-slack-alert-resource#54]
When using the `:latest` image, it is broken for me:

```
ailed to pull image arbourd/concourse-slack-alert-resource@sha256:0ae8529b5f9bfd2a0be018b0420e54ed89a16e435a6a510af66f31bc1a7f3415.
resource script '/opt/resource/in [/tmp/build/get]' failed: exit status 1
```

Are some layers broken or something - not sure how this cold potentially happen. Using `:master` was no problem though

**Comment by EugenMayer** [comment]
seems to be an issue with my concourse installation - the first fetch of a new resource is aways broken, next run is fine since it exists - it's not an issue with slack-alert in particular - sorry

**Comment by arbourd** [comment]
No worries :)
