### ISSUE TITLE
No link to the build in the post in mattermost due to Footer not supported

### ISSUE THREAD

**Issue by EugenMayer** [arbourd/concourse-slack-alert-resource#55]
I am not sure this is somehow related to the fact that i use mattermost, not slack, but when e.g. having a success message, the post does not include a link:

![image](https://user-images.githubusercontent.com/136934/62005474-2a716100-b134-11e9-8032-785e5d756c5c.png)

Any hints on how that could potentially happen - what special structure payload is used for link?

If templates #53 would be supported, i could do that with "message" myself.

**Comment by EugenMayer** [comment]
checking https://github.com/arbourd/concourse-slack-alert-resource/blob/master/out/alert.go i cannot see how this is actually the case ever? Seeing the screenshots in the readme it seems to be the case though. Am i missing something?

**Comment by EugenMayer** [comment]
Ok if found

- https://github.com/arbourd/concourse-slack-alert-resource/blob/master/concourse/build.go#L52
- which is then consumed in https://github.com/arbourd/concourse-slack-alert-resource/blob/master/out/main.go#L21

And footer is part of the payload i guess ( and might not be properly supported by mattermost )

**Comment by EugenMayer** [comment]
Yes, found the official statement for that: https://docs.mattermost.com/developer/message-attachments.html#known-issues

Asking myself if: 
- introducing a new `source` option `api_type` which is be default of course `slack` but can be set to `mattermost`
- the use `title_link` for the link option

I understand this could probably become fairly spagetty and considering how this resource is named, maybe not perfect either. 

On the other side, the link is probably the only reason one would reconsider using this resource for mattermost - other then that it is plain awesome.

Maybe even addig `title_link` in general, without a switch, would work, since Slack will most probably just ignore that field

**Comment by arbourd** [comment]
I don't want to support Mattermost, as this is built for Slack first and foremost. Feel free to fork this and make a Mattermost alert resource :) 

If you have any suggestions that work for both Slack and Mattermost that's okay too, but I don't want to support two APIs at the same time.

**Comment by EugenMayer** [comment]
i think you are most probably right, if you are not interested in having this one supporting both a dedicated way, i might just for your project for mattermost. I love the way you architectured it, it's already go and not some bashism like most other slack resources - lovely.
 
But before i fork, i usually talk to the author to see if forking or sticking heads is the best way - both ways are legitimate.

Thanks for your effort!

**Comment by arbourd** [comment]
Thanks for understanding and I appreciate the nice comments :D
