### ISSUE TITLE
Error Authenticating with Concourse 6.5.0

### ISSUE THREAD

**Issue by cpmccle** [arbourd/concourse-slack-alert-resource#65]
Since I have updated to Concourse v6.5.1when the slack notification resources is used it fails with message "error getting last build status: error requesting Concourse build status: unexpected status code: 401".

Concourse release v6.5.0 (https://github.com/concourse/concourse/releases/tag/v6.5.0) contained breaking changes; including breaking changes affecting "custom automation built around Concourse that authenticates with the Concourse API".  

Is the slack notification resource concourse authentication flow affected by the breaking change and causing the issues I am seeing?

**Comment by arbourd** [comment]
Most likely.

**Comment by arbourd** [comment]
Can you try using `v0.10.0` if this resource and let me know how it goes? There's a small possibility that it works.

**Comment by arbourd** [comment]
Actually, that won't work because of endpoints. 

Can you try `docker.io/arbourd/concourse-slack-alert-resource:wip-6.5`?

https://hub.docker.com/layers/arbourd/concourse-slack-alert-resource/wip-6.5/images/sha256-1a27513e95b12d1ac7a70d80b9812aacaaa95f719d9a5c7c7ef9f594ab6027fa

**Comment by cpmccle** [comment]
That fixed the errors I was seeing, Thanks!

**Comment by arbourd** [comment]
Awesome! I will do a full release. Thank you for being my QA.

**Comment by arbourd** [comment]
v0.12.0 has been released. 

In ~5 mins or so both `latest` and tagged `v0.12.0` will appear in Docker Hub. The wip-6.5 tag will be deleted in 24h so please migrate!

Thanks again!
