### ISSUE TITLE
Message param does not recognize concourse parameters

### ISSUE THREAD

**Issue by tanjoht** [arbourd/concourse-slack-alert-resource#73]
When using the message: parameter, the string does not replace the built in concourse parameters with the proper values.

ie:
    - put: slack-alert
      params: 
        alert_type: failed
        message: "${BUILD_TEAM_NAME} Vault Smoke Tests Failed. Refer to the Runbooks at: none yet"

output in slack:
${BUILD_TEAM_NAME} Vault Smoke Tests Failed. Refer to the Runbooks at: none yet

**Comment by arbourd** [comment]
I'm going to close this because it's not actionable.
