### ISSUE TITLE
Require image for ARM64 architecture

### ISSUE THREAD

**Issue by odidev** [arbourd/concourse-slack-alert-resource#74]
Hi team,

I am trying to use **arbourd/concourse-slack-alert-resource** on ARM64 architecture but it seems the arm64 tag is not available in Docker Hub.

I have successfully built the image using the command **docker build -t <image_name> .** on arm64 platform without any changes.

I have used buildx in Github actions to build and push the image for both platforms.

**Commit Link** - https://github.com/odidev/concourse-slack-alert-resource/commit/d28ff39a48aac01570b9d4249b1d1dbfe214d8b1

**Github actions Link** - https://github.com/odidev/concourse-slack-alert-resource/runs/1820414170?check_suite_focus=true

**Dockerhub Link** - https://hub.docker.com/repository/docker/odidev/concourse-slack-alert-resource

Please share your opinion on this. If interested, I will raise a PR.

**Comment by arbourd** [comment]
Ya, moving away from Docker Hub for builds is probably a good idea. I will accept a Github Actions PR. I will need to edit it a bunch, but we could get it in soon. Thanks!

**Comment by odidev** [comment]
I have raised a PR.

**PR Link** - https://github.com/arbourd/concourse-slack-alert-resource/pull/75

**Comment by arbourd** [comment]
Released with [v0.14.1](https://github.com/arbourd/concourse-slack-alert-resource/releases/tag/v0.14.1)
