### ISSUE TITLE
fixed/broke AUTH not working with oauth2

### ISSUE THREAD

**Issue by qlikcoe** [arbourd/concourse-slack-alert-resource#77]
Seeing this when using v0.14.1 of the resource in Concourse 7

```
error getting last build status: error connecting to Concourse: oauth2: cannot fetch token: 404 Not Found
Response: 404 page not found
```

**Comment by arbourd** [comment]
So as far as I can understand, the url should still be working `/sky/issuer`. Not sure why that's 404ing.

**Comment by qlikcoe** [comment]
There is a possibility it's a misconfiguration on our side. I will close this issue once I get the confirmation. 

Thanks for looking into this 👍

**Comment by qlikcoe** [comment]
@arbourd 
Small update. 
We had two separate issues. 

One was a bunch of 401s (our fault, we accidentally removed localuser credentials for the resource and it was failing for `fixed` and `broke` alert types for the pipelines that were not exposed). That's fixed now, we're passing basic auth creds for every single slack-alert resource instance. 

The second issue is weird. It's 404: 

<img width="1731" alt="Screen Shot 2021-03-31 at 11 41 59" src="https://user-images.githubusercontent.com/33262478/113172134-24d7f280-9216-11eb-8c7c-dae9d0fb969a.png">

Apparently coming from here: 
https://github.com/arbourd/concourse-slack-alert-resource/blob/d4dcc783df8ab1014c3cc2e87b0146c674b7a6a4/out/main.go#L89

Why is it complaining about oauth2? Also, is there a chance the API path has been changed for that request and that's why it's 404?

**Comment by arbourd** [comment]
> Also, is there a chance the API path has been changed for that request and that's why it's 404?

Yes this is possible and has happened a few times before. Most of the bugs that show up here are correcting / adding credentials for major version changes. What's strange tho, is that the endpoint **has not changed** in v7. It's still `/sky/issuer/token`: 
- https://github.com/arbourd/concourse-slack-alert-resource/blob/main/concourse/client.go#L90
- https://github.com/concourse/concourse/blob/eb493819e7064efdcb49b804523ddd40f611681b/atc/atccmd/command.go#L1805

Could be other reasons why it's 404ing though. Unfortunately I haven't run Concourse in years so I'm kinda 100% dependent on other people to test against their clusters 😅

**Comment by arbourd** [comment]
Any updates @qlikcoe? Could it be related to #80?

**Comment by qlikcoe** [comment]
@arbourd  We still have this issue in some places for some weird reason. Not blocking us, been busy lately so didn't have a chance to dog deeper 😢

**Comment by arbourd** [comment]
Closing for now because of time passed, but reopen if it's still here.
