### ISSUE TITLE
Alert types `fixed` and `broke` fail for instanced pipelines with `error getting last build status: error requesting Concourse build status: unexpected status code: 404`

### ISSUE THREAD

**Issue by smoke** [arbourd/concourse-slack-alert-resource#80]
There is an issue with the new experimental [Concourse Instanced Pipelines/Instance Groups](https://concourse-ci.org/instanced-pipelines.html#instanced-pipelines), when the slack-alert resource tries to get the previous build status it fails with `error getting last build status: error requesting Concourse build status: unexpected status code: 404`

The instanced pipelines include instance vars as additional query parameters to the one and the same pipeline path e.g. `https://ci.example.com/teams/development/pipelines/docker-images-build/jobs/build-something/builds/8?vars.instance=%22master%22&vars.team=%22common%22`, apparently the instance parameters are not used when the slack-alert checks the previous build status.
There is a new [$BUILD_PIPELINE_INSTANCE_VARS available for custom resources as metadata](https://concourse-ci.org/implementing-resource-types.html#resource-metadata) that should be used when querying for prev build status.
> $BUILD_PIPELINE_INSTANCE_VARS
>     The instance vars of the instanced pipeline that the build's job lives in, serialized as JSON. See Grouping Pipelines for a definition of instanced pipelines.

**Comment by arbourd** [comment]
We will need to look into how to make this backwards compatible. Perhaps if these env vars are non-nil?

**Comment by funkypenguin** [comment]
We've encountered this after transitioning our pipelines to the new instance pipelines - happy to provide debugging/details if it helps :)

**Comment by arbourd** [comment]
Was this fixed with [v0.16.0](https://github.com/arbourd/concourse-slack-alert-resource/releases/tag/v0.16.0)?

**Comment by smoke** [comment]
I haven't tested it, bit it seems this is fixed by https://github.com/arbourd/concourse-slack-alert-resource/pull/86

**Comment by arbourd** [comment]
Thanks @smoke I'll close for now and hopefully there is no need to reopen 🤞🏻

**Comment by smoke** [comment]
@arbourd I specifically tested it today, the issue is still not fixed with v0.16.0 can you please reopen it :(

**Comment by arbourd** [comment]
I'm happy to accept PRs for this but it's been so many years since I used Concourse that I'm unlikely to get around to it myself. Sorry! 🥲

**Comment by smoke** [comment]
I have been looking to try Go development for some time now, also I am so sad about this bug - that I am planning to give it a try :muscle:
