### ISSUE TITLE
Looking for a new maintainer

### ISSUE THREAD

**Issue by arbourd** [arbourd/concourse-slack-alert-resource#84]
Hey folks,

I haven't used Concourse for almost 3 years and keeping this up-to-date can be a bit of a problem. 

Would anyone who uses this resource regularly like to take over some of the maintenance?

**Comment by smoke** [comment]
@arbourd I would like to volunteer. We are still using Concourse CI and this fine resource is of good use to us, so for the time being I can spare some time to maintain it.

**Comment by arbourd** [comment]
Sounds good @smoke. I've invited you to be a collaborator. Check your email 😁

**Comment by smoke** [comment]
@arbourd Thank you, I will try to take a good care and I will appreciate your help in between!

**Comment by smoke** [comment]
@arbourd I am really sorry, but I would like to step away from a collaborator on this project. 

- I see you are taking a good care of it recently
- I don't use Concourse CI recently and totally lack the time to be involved

Thank you for this great project, keep it going!
