### ISSUE TITLE
Add retry logic for Slack http requests

### ISSUE THREAD

**Issue by phoenix090** [arbourd/concourse-slack-alert-resource#94]
Hi

We are getting this error quite frequently when sending notifications to slack:

`wait for process completion: connection: decode failed: read tcp 127.0.0.1:49532->127.0.0.1:45955: read: connection reset by peer`

I understand `connection reset by peer` occurs when when a peer (the other end) unexpectedly closes the underlying connection. But i'm simply wondering if there is a way to configure retries when this occurs. Thanks in advance.

**Comment by arbourd** [comment]
Happy to accept a PR for this! I haven't used Concourse in years so I'm a bit out of the loop
